[project]
name = "leabhar-cliste"
version = "0.1.0"
description = "Programming practices, principles and concepts."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mdx-truly-sane-lists==1.3",
    "mkdocs-material==9.6.15",
    "pre-commit==3.3.3",
]
